# Generated by Django 5.2.8 on 2025-11-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_published_post_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
