# Generated by Django 5.2.8 on 2026-05-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
