# Generated by Django 5.1 on 2026-07-06 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome'), ('abandoned_cart', 'Abandoned Cart'), ('order_confirmation', 'Order Confirmation'), ('post_purchase', 'Post-Purchase Follow-Up'), ('winback', 'Win-Back'), ('new_drop', 'New Drop Alert'), ('anniversary', 'Anniversary'), ('back_in_stock', 'Back in Stock')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'email_type', 'sent_at'], name='main_emaill_user_id_31d1b1_idx')],
            },
        ),
    ]
